### PR TITLE
Fix scale issues with labels and trend indicators in SimpleBarChart

### PR DESCRIPTION
**Pull request by acmertz**
## What does this implement/fix?

Fixes the following issues with `<SimpleBarChart>`:

- Label width is subtracted twice from the maximum available chart width, with the effect that horizontal bars didn't take up as much space as they could have (#1544)
- Trend indicators can truncate horizontal bars and make different values display the same width (#1552)
- Trend indicators are not taken into account when calculating the horizontal scale and can overflow the chart bounds (#1553)

See this [sandbox](https://codesandbox.io/s/shopify-polaris-viz-react-typescript-playground-forked-q9g3st?file=/src/index.tsx) for an example (also linked from the original issue). The issue is especially apparent for bars with long labels, where the double subtraction can make the bar lengths extremely small despite the relatively large amount of available space.

### Available width:

Screenshot 2023-06-27 at 10 18 00

### Bar + label doesn't use all available space:

Screenshot 2023-06-27 at 10 18 07

## Does this close any currently open issues?

Fixes #1544, #1552, #1553

### Before:

Screenshot 2023-06-27 at 13 43 04

### After:

Screenshot 2023-06-27 at 13 43 21
 
## Storybook link

https://6062ad4a2d14cd0021539c1b-qxmjknhics.chromatic.com/?path=/docs/polaris-viz-charts-simplebarchart--long-labels

Check each of the `SimpleBarChart` stories to confirm that this change doesn't adversely impact other use cases for this chart type.

### Before merging

- [x] Check your changes on a variety of [browsers](https://help.shopify.com/en/manual/shopify-admin/supported-browsers) and devices.

- [x] Update the Changelog's Unreleased section with your changes.

- [x] Update relevant documentation, tests, and Storybook.

### CODE REVIEW

**Review by pbojinov — APPROVED** [review]
This generally looks good to me. 

Adding @envex on here as a reviewer as well since he's the one that's most recently worked on this part of the code base. Would appreciate his sanity check 🙏🏼

**Review by envex — CHANGES_REQUESTED** [review]
This is looking good, except it's breaking the [Trend With All Negative](https://shopify.chromatic.com/component?appId=6062ad4a2d14cd0021539c1b&csfId=polaris-viz-chromatic-charts-simplebarchart&specName=Trend%20With%20All%20Negative&buildNumber=1155) test case.

https://shopify.chromatic.com/test?appId=6062ad4a2d14cd0021539c1b&id=649b316a3d0a5ffbedc2f4e1

You can run the chromatic tests locally by running `yarn storybook:all`.

**Comment by acmertz** [comment]
> This is looking good, except it's breaking the [Trend With All Negative](https://shopify.chromatic.com/component?appId=6062ad4a2d14cd0021539c1b&csfId=polaris-viz-chromatic-charts-simplebarchart&specName=Trend%20With%20All%20Negative&buildNumber=1155) test case.
> 
> https://shopify.chromatic.com/test?appId=6062ad4a2d14cd0021539c1b&id=649b316a3d0a5ffbedc2f4e1
> 
> You can run the chromatic tests locally by running `yarn storybook:all`.

Thanks @envex for the feedback! I set the `zeroPosition` back to `xScale(0)` in c6349643d59dbbddf5bb5cd2980cd5e167d281ac and it seems to have improved the [Trend With All Negative](https://shopify.chromatic.com/test?appId=6062ad4a2d14cd0021539c1b&id=649c6bf84597764ee13f6fce) test case, but caused some issues for some of the test cases with trend indicators. 

[useHorizontalXScale()](https://github.com/Shopify/polaris-viz/blob/main/packages/polaris-viz/src/hooks/useHorizontalXScale.ts) doesn't appear to take trend indicators into account, which is made more obvious with my PR because it removes the extra "buffer space" that the double label width subtraction was creating. When coupled with the clamping behavior that was added in https://github.com/Shopify/polaris-viz/pull/1539, it can cause the trend indicator to be clipped at the right edge of the chart like in the [Trend With Mixed Values](https://shopify.chromatic.com/test?appId=6062ad4a2d14cd0021539c1b&id=649c6bf84597764ee13f6fd0) test case. I created #1552 and #1553 to document the horizontal scaling bugs with trend indicators since they're a separate issue from what I'm trying to fix with this PR.

In the meantime, I'm curious to hear your thoughts on whether we can move forward with this fix or if one/both of the above issues should be resolved first. 🤔

**Comment by acmertz** [comment]
> 



> @acmertz Ideally we should fix them all in this PR, or have a fast follow PR that fixes the TrendIndicator issue.
> 
> Basically, we shouldn't release a new version until both issues have been merged to main.
> 
> If you want, I can take a look in the morning - otherwise you can take a stab at adding the longest trend indicator length to `[useHorizontalXScale()](https://github.com/Shopify/polaris-viz/blob/main/packages/polaris-viz/src/hooks/useHorizontalXScale.ts)`.

Happy to give it a shot! 😄 I will make another PR for it.

**Review by pbojinov — APPROVED** [review]
Changes look good to me. Especially when looking at the diff snapshots in Storybook, we're seeing a lot more of the bar charts 📊 ✅  

Before on the right and After on the left
image

**Review by envex — APPROVED** [review]

**Pull request merged**
